### ISSUE TITLE
unable to compile -  Unable to find current revision in submodule path 'components/esp-adf-libs

### ISSUE THREAD

**Issue by pimp1310** [gnumpi/esphome_audio#33]
hello,

i tried to compile but i always get  a error, i dont know what exactly he wants. i think he cant fetch the esp-adf component?

i tried it with this version, 
https://github.com/gnumpi/esphome_audio/blob/main/examples/esp32-s3-N16R8-adf.yaml

`INFO ESPHome 2024.4.1
INFO Reading configuration /config/esphome/v-assist-kitchen-esp32nr168.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-adf.git@v2.5
INFO Updating submodules (components/esp-adf-libs, components/esp-sr) for https://github.com/espressif/esp-adf.git@v2.5
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1061, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1048, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 478, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 193, in write_cpp
    return write_cpp_file()
           ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 211, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 344, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 297, in copy_src_tree
    copy_files()
  File "/esphome/esphome/components/esp32/__init__.py", line 685, in copy_files
    repo_dir, _ = git.clone_or_update(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/git.py", line 111, in clone_or_update
    run_git_command(
  File "/esphome/esphome/git.py", line 31, in run_git_command
    raise cv.Invalid(lines[-1][len("fatal: ") :])
voluptuous.error.Invalid: Unable to find current revision in submodule path 'components/esp-adf-libs'`

here is my config

https://pastebin.com/4KuYS7GG

Thank You!

**Comment by gnumpi** [comment]
Hey, sorry I can't reproduce your error. It seems something is wrong with your general build setup. Can you retry with a fresh setup?

**Comment by pimp1310** [comment]
@gnumpi 

You mean reinstall esphome ? 
Or only the sketch?

**Comment by pimp1310** [comment]
@gnumpi 

now it works. i reinstalled esphome addon.

But the whole Esp Device reboots when i use the media_player function with a automation to play for example a mp3, but i make a new post for this.
